server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh # 路由的id，没有固定规则，唯一，建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getById/**    # 断言，路径相匹配进行路由
        - id: payment_routh # 路由的id，没有固定规则，唯一，建议配合服务名
          # lb 负载均衡协议
          uri: lb://CLOUD-PAYMENT-SERVICE  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
#            - After=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
#            - Before=2021-03-08T10:59:34.102+08:00[Asia/Shanghai]
#            - Between=2020-03-08T10:59:34.102+08:00[Asia/Shanghai],2021-03-08T10:59:34.102+08:00[Asia/Shanghai]
#            - Cookie=username,zhao #并且Cookie是username=zhao才能访问
#            - Header=X-Request-Id,\d+ #请求头中要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.zhao.com
#            - Method=GET
#            - Query=username, \d+ #要有参数名称并且是正整数才能路由
#          filters:
#            - AddRequestHeader=X-Request-Id, 1024
      # 支持通过注册中心进行服务发现
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
       register-with-eureka : true
       fetch-registry : true
       defaultZone : http://eureka7001.com:7001/eureka/